
version: "3.3"

services:
  postgres:
    image: postgres:16
    networks:
      - internal
    ports:
      - 5612:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pranesimai
      TZ: 'Etc/GMT'
      PGTZ: 'Etc/GMT'

  redis:
    image: redis:latest
    networks:
      - internal
    ports:
      - 6612:6379

  viisp-auth-helper:
    image: ghcr.io/aplinkosministerija/viisp-auth-helper:1.1.0
    environment:
      VIISP_PID: ${VIISP_PID}
      KEYSTORE_BASE64: ${VIISP_KEYSTORE_BASE64}
      KEYSTORE_PASSWORD: ${VIISP_KEYSTORE_PASSWORD}
      VIISP_POSTBACK_URL: ${VIISP_POSTBACK_URL}
    ports:
      - 8080:8080

networks:
  internal:

volumes:
  data:
